route:
  receiver: discord
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: discord
    slack_configs:
      - api_url: 'https://discord.com/api/webhooks/1517564415363387603/GOksgqJMG3lmwGqxHsA3rQK9KFjz7BJ3x1Q-M0AsqmMXTML9TTWrsSa3eEGEjE1osW-P/slack'
        channel: '#alerts'
        send_resolved: true
        title: '{{ .CommonAnnotations.summary }}'
        text: '{{ .CommonAnnotations.description }}'