groups:
  - name: basic_alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance is down"
          description: "Target unreachable for 1 minute."
      - alert: HighCPU
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU"
          description: "CPU above 80% for 2 minutes."
      - alert: HighErrorRate
        expr: rate(app_errors_total[2m]) / rate(app_requests_total[2m]) > 0.1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Taux d'erreur élevé"
          description: "Plus de 10% des requêtes échouent depuis 1 minute."